export { default as Componentes } from "./Componentes.astro"
export { default as ButtonRouter } from "./ButtonRouter.astro"
export { default as ButtonGeneral } from "./ButtonGeneral.jsx"
export { default as CustomImagen } from "./CustomImagen.astro"
export { default as Counter } from "./Counter.jsx"
export { default as MenuView } from "./MenuView.jsx"