import { Servicio } from "../interfaces/ServiciosAgendamientoCardsInterface"
import image1 from "@img/fotos/1.jpg"
import image3 from "@img/fotos/3.jpg"
import image4 from "@img/fotos/4.jpg"
import image6 from "@img/fotos/6.jpg"
import image7 from "@img/fotos/7.jpg"
import image9 from "@img/fotos/9.jpg"
import image10 from "@img/fotos/10.jpg"
import image12 from "@img/fotos/12.jpg"
import image13 from "@img/fotos/13.jpg"
import image14 from "@img/fotos/14.jpg"
import image15 from "@img/fotos/15.jpg"
import image16 from "@img/fotos/16.jpg"
import image17 from "@img/fotos/17.jpg"
import image18 from "@img/fotos/18.jpg"
import image19 from "@img/fotos/19.jpg"
import image20 from "@img/fotos/20.jpg" 

export const servicios: Servicio[] = [
    {
      id: 'corte',
      nombre: 'Corte de cabello',
      descripcion: 'Corte de cabello con acabado profesional',
      precio: 30000,
      duracion: 30,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: image1,
      imgPrincipalServiceView: false,
      img2: image3,
      img3: image4,
      img4: image6,
      img5: image7,
      img6: image9,
      video: 'https://www.youtube.com/embed/YBN2aj5H0fY',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: false,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'barba',
      nombre: 'Arreglo de barba',
      descripcion: 'Arreglo y perfilado de barba',
      precio: 20000,
      duracion: 15,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: image16,
      imgPrincipalServiceView: false,
      img2: image10,
      img3: image12,
      img4: image13,
      img5: image14,
      img6: image15,
      video: 'https://www.youtube.com/embed/Gzj0aaLztZE',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: false,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'cejas',
      nombre: 'Cejas con navaja',
      descripcion: 'Diseño y perfilado de cejas',
      precio: 15000,
      duracion: 15,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: image17,
      imgPrincipalServiceView: false,
      img2: image18,
      img3: image19,
      img4: image20,
      img5: image6,
      img6: image9,
      video: 'https://www.youtube.com/embed/chTq7B2-HXo',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: false,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'corte-barba',
      nombre: 'Corte + Barba',
      descripcion: 'Corte de cabello con arreglo de barba',
      precio: 45000,
      duracion: 45,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: image12,
      imgPrincipalServiceView: false,
      img2: image1,
      img3: image15,
      img4: image9,
      img5: image4,
      img6: image10,
      video: 'https://www.youtube.com/embed/dcF7ftxfNKI',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: false,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'corte-cejas',
      nombre: 'Corte + Cejas',
      descripcion: 'Corte de cabello con diseño de cejas',
      precio: 40000,
      duracion: 45,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: image7,
      imgPrincipalServiceView: false,
      img2: image4,
      img3: image12,
      img4: image18,
      img5: image20,
      img6: image3,
      video: 'https://www.youtube.com/embed/Ok0EYJ26iws',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: false,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'completo',
      nombre: 'Corte + Barba + Cejas',
      descripcion: 'Servicio completo de barbería',
      precio: 60000,
      duracion: 60,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: image13,
      imgPrincipalServiceView: false,
      img2: image6,
      img3: image12,
      img4: image17,
      img5: image13,
      img6: image14,
      video: 'https://www.youtube.com/embed/YjT25DCtIx0',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: false,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'  
    },
    {
      id: 'colorimetria',
      nombre: 'Colorimetría',
      descripcion: 'Tinte y coloración profesional',
      precio: 80000,
      duracion: 90,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: image20,
      imgPrincipalServiceView: false,
      img2: image4,
      img3: image12,
      img4: image13,
      img5: image16,
      img6: image9,
      video: 'https://www.youtube.com/embed/BBO71cVQW0Y',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: false,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'delineado',
      nombre: 'Delineado',
      descripcion: 'Delineado de barba y bigote',
      precio: 10000,
      duracion: 15,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: image15,
      imgPrincipalServiceView: false,
      img2: image16,
      img3: image12,
      img4: image13,
      img5: image3,
      img6: image20,
      video: 'https://www.youtube.com/embed/HeIQywUytGA',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: false,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    }
  ]