import { Servicio } from "../interfaces/ServiciosAgendamientoCardsInterface";

export const servicios: Servicio[] = [
    {
      id: 'corte',
      nombre: 'Corte de cabello',
      descripcion: 'Corte de cabello con acabado profesional',
      precio: 30000,
      duracion: 30,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: '/img/servicios/corte-cabello.jpg',
      imgPrincipalServiceView: false,
      img2: '/img/servicios/corte-cabello-2.jpg',
      img3: '/img/servicios/corte-cabello-3.jpg',
      img4: '/img/servicios/corte-cabello-2.jpg',
      img5: '/img/servicios/corte-cabello-3.jpg',
      img6: '/img/servicios/corte-cabello-3.jpg',
      video: 'https://www.youtube.com/embed/abc123',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: true,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'barba',
      nombre: 'Arreglo de barba',
      descripcion: 'Arreglo y perfilado de barba',
      precio: 20000,
      duracion: 15,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: '/img/servicios/arreglo-barba.jpg',
      imgPrincipalServiceView: false,
      img2: '/img/servicios/corte-cabello-2.jpg',
      img3: '/img/servicios/corte-cabello-3.jpg',
      img4: '/img/servicios/corte-cabello-2.jpg',
      img5: '/img/servicios/corte-cabello-3.jpg',
      img6: '/img/servicios/corte-cabello-3.jpg',
      video: 'https://www.youtube.com/embed/abc123',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: true,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'cejas',
      nombre: 'Cejas con navaja',
      descripcion: 'Diseño y perfilado de cejas',
      precio: 15000,
      duracion: 15,
      typeDuration: "minutos",
      priceView: false,
      isActive: false,
      imgPrincipalService: '/img/servicios/arreglo-barba.jpg',
      imgPrincipalServiceView: false,
      img2: '/img/servicios/corte-cabello-2.jpg',
      img3: '/img/servicios/corte-cabello-3.jpg',
      img4: '/img/servicios/corte-cabello-2.jpg',
      img5: '/img/servicios/corte-cabello-3.jpg',
      img6: '/img/servicios/corte-cabello-3.jpg',
      video: 'https://www.youtube.com/embed/abc123',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: true,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'corte-barba',
      nombre: 'Corte + Barba',
      descripcion: 'Corte de cabello con arreglo de barba',
      precio: 45000,
      duracion: 45,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: '/img/servicios/arreglo-barba.jpg',
      imgPrincipalServiceView: false,
      img2: '/img/servicios/corte-cabello-2.jpg',
      img3: '/img/servicios/corte-cabello-3.jpg',
      img4: '/img/servicios/corte-cabello-2.jpg',
      img5: '/img/servicios/corte-cabello-3.jpg',
      img6: '/img/servicios/corte-cabello-3.jpg',
      video: 'https://www.youtube.com/embed/abc123',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: true,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'corte-cejas',
      nombre: 'Corte + Cejas',
      descripcion: 'Corte de cabello con diseño de cejas',
      precio: 40000,
      duracion: 45,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: '/img/servicios/arreglo-barba.jpg',
      imgPrincipalServiceView: false,
      img2: '/img/servicios/corte-cabello-2.jpg',
      img3: '/img/servicios/corte-cabello-3.jpg',
      img4: '/img/servicios/corte-cabello-2.jpg',
      img5: '/img/servicios/corte-cabello-3.jpg',
      img6: '/img/servicios/corte-cabello-3.jpg',
      video: 'https://www.youtube.com/embed/abc123',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: true,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'completo',
      nombre: 'Corte + Barba + Cejas',
      descripcion: 'Servicio completo de barbería',
      precio: 60000,
      duracion: 60,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: '/img/servicios/arreglo-barba.jpg',
      imgPrincipalServiceView: false,
      img2: '/img/servicios/corte-cabello-2.jpg',
      img3: '/img/servicios/corte-cabello-3.jpg',
      img4: '/img/servicios/corte-cabello-2.jpg',
      img5: '/img/servicios/corte-cabello-3.jpg',
      img6: '/img/servicios/corte-cabello-3.jpg',
      video: 'https://www.youtube.com/embed/abc123',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: true,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'  
    },
    {
      id: 'colorimetria',
      nombre: 'Colorimetría',
      descripcion: 'Tinte y coloración profesional',
      precio: 80000,
      duracion: 90,
      typeDuration: "minutos",
      priceView: false,
      isActive: true,
      imgPrincipalService: '/img/servicios/arreglo-barba.jpg',
      imgPrincipalServiceView: false,
      img2: '/img/servicios/corte-cabello-2.jpg',
      img3: '/img/servicios/corte-cabello-3.jpg',
      img4: '/img/servicios/corte-cabello-2.jpg',
      img5: '/img/servicios/corte-cabello-3.jpg',
      img6: '/img/servicios/corte-cabello-3.jpg',
      video: 'https://www.youtube.com/embed/abc123',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: true,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    },
    {
      id: 'delineado',
      nombre: 'Delineado',
      descripcion: 'Delineado de barba y bigote',
      precio: 10000,
      duracion: 15,
      typeDuration: "minutos",
      priceView: false,
      isActive: false,
      imgPrincipalService: '/img/servicios/arreglo-barba.jpg',
      imgPrincipalServiceView: false,
      img2: '/img/servicios/corte-cabello-2.jpg',
      img3: '/img/servicios/corte-cabello-3.jpg',
      img4: '/img/servicios/corte-cabello-2.jpg',
      img5: '/img/servicios/corte-cabello-3.jpg',
      img6: '/img/servicios/corte-cabello-3.jpg',
      video: 'https://www.youtube.com/embed/abc123',
      allDetailsService: 'El corte de cabello incluye lavado, corte personalizado según tu preferencia y acabado profesional.',
      viewDetailsService: true,
      serviceInSede: true,
      sedesService: [1], 
      serviceForPerson: true,
      peopleProvideService: [1,2],
      sheduDependOf: 'person'
    }
  ]