import {
  AlertCircle,
  Airplay,
  AlertOctagon,
  Anchor,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BarChart,
  Bell,
  Bookmark,
  Box,
  Briefcase,
  Building,
  Calendar,
  Camera,
  Car,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Cloud,
  CloudDrizzle,
  Codepen,
  Coffee,
  CreditCard,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  File,
  FileText,
  Filter,
  Flag,
  Folder,
  Gift,
  Globe,
  Grid,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Key,
  Layers,
  Lightbulb,
  Link,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  Mic,
  MinusCircle,
  Monitor,
  Music,
  Package,
  Paperclip,
  Pause,
  Phone,
  PlusCircle,
  Printer,
  Receipt,
  Repeat,
  Rewind,
  Scissors,
  Search,
  Server,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  Sliders,
  Smartphone,
  Store,
  Star,
  Timer,
  Terminal,
  ThumbsUp,
  Trash2,
  Truck,
  Unlock,
  Upload,
  User,
  Users,
  Video,
  Wallet,
  Wifi,
  Zap,
  ZoomIn,
  ZoomOut
} from 'lucide-react'

export const colorOptionsStage4 = [
  { value: 'red', name: 'Rojo', titleShade: 700, detailShade: 600 },
  { value: 'orange', name: 'Naranja', titleShade: 700, detailShade: 600 },
  { value: 'amber', name: 'Ámbar', titleShade: 700, detailShade: 600 },
  { value: 'yellow', name: 'Amarillo', titleShade: 700, detailShade: 600 },
  { value: 'lime', name: 'Lima', titleShade: 700, detailShade: 600 },
  { value: 'green', name: 'Verde', titleShade: 700, detailShade: 600 },
  { value: 'emerald', name: 'Esmeralda', titleShade: 700, detailShade: 600 },
  { value: 'teal', name: 'Verde azulado', titleShade: 700, detailShade: 600 },
  { value: 'cyan', name: 'Cian', titleShade: 700, detailShade: 600 },
  { value: 'sky', name: 'Celeste', titleShade: 700, detailShade: 600 },
  { value: 'blue', name: 'Azul', titleShade: 700, detailShade: 600 },
  { value: 'indigo', name: 'Índigo', titleShade: 700, detailShade: 600 },
  { value: 'violet', name: 'Violeta', titleShade: 700, detailShade: 600 },
  { value: 'purple', name: 'Morado', titleShade: 700, detailShade: 600 },
  { value: 'fuchsia', name: 'Fucsia', titleShade: 700, detailShade: 600 },
  { value: 'pink', name: 'Rosado', titleShade: 700, detailShade: 600 },
  { value: 'rose', name: 'Rosa', titleShade: 700, detailShade: 600 },
  { value: 'slate', name: 'Pizarra', titleShade: 700, detailShade: 600 },
  { value: 'zinc', name: 'Zinc', titleShade: 700, detailShade: 600 },
  { value: 'gray', name: 'Gris', titleShade: 700, detailShade: 600 },
  { value: 'neutral', name: 'Neutral', titleShade: 700, detailShade: 600 },
  { value: 'stone', name: 'Piedra', titleShade: 700, detailShade: 600 }
]

export const colorClassMapStage4 = {
  red: { 500: 'text-red-500', 600: 'text-red-600', 700: 'text-red-700' },
  orange: { 500: 'text-orange-500', 600: 'text-orange-600', 700: 'text-orange-700' },
  amber: { 500: 'text-amber-500', 600: 'text-amber-600', 700: 'text-amber-700' },
  yellow: { 500: 'text-yellow-500', 600: 'text-yellow-600', 700: 'text-yellow-700' },
  lime: { 500: 'text-lime-500', 600: 'text-lime-600', 700: 'text-lime-700' },
  green: { 500: 'text-green-500', 600: 'text-green-600', 700: 'text-green-700' },
  emerald: { 500: 'text-emerald-500', 600: 'text-emerald-600', 700: 'text-emerald-700' },
  teal: { 500: 'text-teal-500', 600: 'text-teal-600', 700: 'text-teal-700' },
  cyan: { 500: 'text-cyan-500', 600: 'text-cyan-600', 700: 'text-cyan-700' },
  sky: { 500: 'text-sky-500', 600: 'text-sky-600', 700: 'text-sky-700' },
  blue: { 500: 'text-blue-500', 600: 'text-blue-600', 700: 'text-blue-700' },
  indigo: { 500: 'text-indigo-500', 600: 'text-indigo-600', 700: 'text-indigo-700' },
  violet: { 500: 'text-violet-500', 600: 'text-violet-600', 700: 'text-violet-700' },
  purple: { 500: 'text-purple-500', 600: 'text-purple-600', 700: 'text-purple-700' },
  fuchsia: { 500: 'text-fuchsia-500', 600: 'text-fuchsia-600', 700: 'text-fuchsia-700' },
  pink: { 500: 'text-pink-500', 600: 'text-pink-600', 700: 'text-pink-700' },
  rose: { 500: 'text-rose-500', 600: 'text-rose-600', 700: 'text-rose-700' },
  slate: { 500: 'text-slate-500', 600: 'text-slate-600', 700: 'text-slate-700' },
  zinc: { 500: 'text-zinc-500', 600: 'text-zinc-600', 700: 'text-zinc-700' },
  gray: { 500: 'text-gray-500', 600: 'text-gray-600', 700: 'text-gray-700' },
  neutral: { 500: 'text-neutral-500', 600: 'text-neutral-600', 700: 'text-neutral-700' },
  stone: { 500: 'text-stone-500', 600: 'text-stone-600', 700: 'text-stone-700' }
}

export const iconOptionsToCard = [
  { name: "Alerta", value: "alert-circle", icon: AlertCircle },
  { name: "Airplay", value: "airplay", icon: Airplay },
  { name: "Alerta Octágono", value: "alert-octagon", icon: AlertOctagon },
  { name: "Ancla", value: "anchor", icon: Anchor },
  { name: "Archivo", value: "archive", icon: Archive },
  { name: "Flecha Abajo", value: "arrow-down", icon: ArrowDown },
  { name: "Flecha Izquierda", value: "arrow-left", icon: ArrowLeft },
  { name: "Flecha Derecha", value: "arrow-right", icon: ArrowRight },
  { name: "Flecha Arriba", value: "arrow-up", icon: ArrowUp },
  { name: "Premio", value: "award", icon: Award },
  { name: "Gráfico de Barras", value: "bar-chart", icon: BarChart },
  { name: "Campana", value: "bell", icon: Bell },
  { name: "Marcador", value: "bookmark", icon: Bookmark },
  { name: "Caja", value: "box", icon: Box },
  { name: "Maletín", value: "briefcase", icon: Briefcase },
  { name: "Edificio", value: "building", icon: Building },
  { name: "Calendario", value: "calendar", icon: Calendar },
  { name: "Cámara", value: "camera", icon: Camera },
  { name: "Carro", value: "car", icon: Car },
  { name: "Check", value: "check-circle", icon: CheckCircle },
  { name: "Chevron Abajo", value: "chevron-down", icon: ChevronDown },
  { name: "Chevron Izquierda", value: "chevron-left", icon: ChevronLeft },
  { name: "Chevron Derecha", value: "chevron-right", icon: ChevronRight },
  { name: "Chevron Arriba", value: "chevron-up", icon: ChevronUp },
  { name: "Círculo", value: "circle", icon: Circle },
  { name: "Nube", value: "cloud", icon: Cloud },
  { name: "Nube Lluvia", value: "cloud-drizzle", icon: CloudDrizzle },
  { name: "Codepen", value: "codepen", icon: Codepen },
  { name: "Café", value: "coffee", icon: Coffee },
  { name: "Tarjeta de Crédito", value: "credit-card", icon: CreditCard },
  { name: "Base de Datos", value: "database", icon: Database },
  { name: "Descargar", value: "download", icon: Download },
  { name: "Editar", value: "edit", icon: Edit },
  { name: "Enlace Externo", value: "external-link", icon: ExternalLink },
  { name: "Ojo", value: "eye", icon: Eye },
  { name: "Archivo", value: "file", icon: File },
  { name: "Archivo de Texto", value: "file-text", icon: FileText },
  { name: "Filtro", value: "filter", icon: Filter },
  { name: "Bandera", value: "flag", icon: Flag },
  { name: "Carpeta", value: "folder", icon: Folder },
  { name: "Regalo", value: "gift", icon: Gift },
  { name: "Globo", value: "globe", icon: Globe },
  { name: "Cuadrícula", value: "grid", icon: Grid },
  { name: "Hash", value: "hash", icon: Hash },
  { name: "Audífonos", value: "headphones", icon: Headphones },
  { name: "Corazón", value: "heart", icon: Heart },
  { name: "Círculo de Ayuda", value: "help-circle", icon: HelpCircle },
  { name: "Casa", value: "home", icon: Home },
  { name: "Imagen", value: "image", icon: Image },
  { name: "Llave", value: "key", icon: Key },
  { name: "Capas", value: "layers", icon: Layers },
  { name: "Bombilla", value: "lightbulb", icon: Lightbulb },
  { name: "Enlace", value: "link", icon: Link },
  { name: "Lista", value: "list", icon: List },
  { name: "Cargador", value: "loader", icon: Loader },
  { name: "Candado", value: "lock", icon: Lock },
  { name: "Iniciar Sesión", value: "log-in", icon: LogIn },
  { name: "Cerrar Sesión", value: "log-out", icon: LogOut },
  { name: "Correo", value: "mail", icon: Mail },
  { name: "Pin de Mapa", value: "map-pin", icon: MapPin },
  { name: "Mensaje", value: "message-circle", icon: MessageCircle },
  { name: "Micrófono", value: "mic", icon: Mic },
  { name: "Círculo Menos", value: "minus-circle", icon: MinusCircle },
  { name: "Monitor", value: "monitor", icon: Monitor },
  { name: "Música", value: "music", icon: Music },
  { name: "Paquete", value: "package", icon: Package },
  { name: "Clip", value: "paperclip", icon: Paperclip },
  { name: "Pausa", value: "pause", icon: Pause },
  { name: "Teléfono", value: "phone", icon: Phone },
  { name: "Círculo Más", value: "plus-circle", icon: PlusCircle },
  { name: "Impresora", value: "printer", icon: Printer },
  { name: "Recibo", value: "receipt", icon: Receipt },
  { name: "Repetir", value: "repeat", icon: Repeat },
  { name: "Rebobinar", value: "rewind", icon: Rewind },
  { name: "Tijeras", value: "scissors", icon: Scissors },
  { name: "Buscar", value: "search", icon: Search },
  { name: "Servidor", value: "server", icon: Server },
  { name: "Escudo", value: "shield", icon: Shield },
  { name: "Escudo Check", value: "shield-check", icon: ShieldCheck },
  { name: "Carrito", value: "shopping-cart", icon: ShoppingCart },
  { name: "Aleatorio", value: "shuffle", icon: Shuffle },
  { name: "Deslizadores", value: "sliders", icon: Sliders },
  { name: "Teléfono Inteligente", value: "smartphone", icon: Smartphone },
  { name: "Tienda", value: "store", icon: Store },
  { name: "Estrella", value: "star", icon: Star },
  { name: "Temporizador", value: "timer", icon: Timer },
  { name: "Terminal", value: "terminal", icon: Terminal },
  { name: "Pulgar Arriba", value: "thumbs-up", icon: ThumbsUp },
  { name: "Basura", value: "trash-2", icon: Trash2 },
  { name: "Camión", value: "truck", icon: Truck },
  { name: "Desbloquear", value: "unlock", icon: Unlock },
  { name: "Subir", value: "upload", icon: Upload },
  { name: "Usuario", value: "user", icon: User },
  { name: "Usuarios", value: "users", icon: Users },
  { name: "Video", value: "video", icon: Video },
  { name: "Billetera", value: "wallet", icon: Wallet },
  { name: "WiFi", value: "wifi", icon: Wifi },
  { name: "Rayo", value: "zap", icon: Zap },
  { name: "Zoom In", value: "zoom-in", icon: ZoomIn },
  { name: "Zoom Out", value: "zoom-out", icon: ZoomOut }
].sort((a, b) => a.name.localeCompare(b.name))







