export const colorOptions = [
    { name: "Red", value: "red", titleShade: 700, paragraphShade: 600 },
    { name: "Orange", value: "orange", titleShade: 700, paragraphShade: 600 },
    { name: "Amber", value: "amber", titleShade: 700, paragraphShade: 600 },
    { name: "Yellow", value: "yellow", titleShade: 700, paragraphShade: 600 },
    { name: "Lime", value: "lime", titleShade: 700, paragraphShade: 600 },
    { name: "Green", value: "green", titleShade: 800, paragraphShade: 600 },
    { name: "Emerald", value: "emerald", titleShade: 900, paragraphShade: 600 },
    { name: "Teal", value: "teal", titleShade: 700, paragraphShade: 600 },
    { name: "Cyan", value: "cyan", titleShade: 800, paragraphShade: 600 },
    { name: "Sky", value: "sky", titleShade: 900, paragraphShade: 600 },
    { name: "Blue", value: "blue", titleShade: 900, paragraphShade: 600 },
    { name: "Indigo", value: "indigo", titleShade: 700, paragraphShade: 600 },
    { name: "Violet", value: "violet", titleShade: 800, paragraphShade: 600 },
    { name: "Purple", value: "purple", titleShade: 800, paragraphShade: 600 },
    { name: "Fuchsia", value: "fuchsia", titleShade: 900, paragraphShade: 600 },
    { name: "Pink", value: "pink", titleShade: 800, paragraphShade: 600 },
    { name: "Rose", value: "rose", titleShade: 800, paragraphShade: 600 },
    { name: "Slate", value: "slate", titleShade: 700, paragraphShade: 600 },
    { name: "Gray", value: "gray", titleShade: 700, paragraphShade: 600 },
    { name: "Zinc", value: "zinc", titleShade: 700, paragraphShade: 600 },
    { name: "Neutral", value: "neutral", titleShade: 900, paragraphShade: 600 },
    { name: "Stone", value: "stone", titleShade: 700, paragraphShade: 600 },
  ]