export { Header } from "./Header"
export { Footer } from "./Footer"
export { Layout } from "./Layout"
export { LayoutGeneral } from "./LayoutGeneral"
export { ButtonRouter, CustomImagen, InicioBienvenida, InicioProductos, InicioServicios, Titulos, Parrafos, Sesion, DivVertical, Picture169Grande, DivHorizontal, CardInfo, ButtonGeneral, MenuView, GoogleAuth, GetImgPerfil, ProductsAll, IconGeneral, InicioRedesSociales, CardRedesSociales} from "./Componentes"
export { Crear, PaginateStages, Stage1, Stage2, Stage3, Stage4, Stage5 } from "./Crear"